# Generated by Django 3.2 on 2021-05-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='isis', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(),
        ),
    ]
