# Generated by Django 3.2 on 2021-06-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210509_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='text',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
